package com.drools.demo;
import com.drools.demo.po.Person;

rule "temp"
salience 10001 // 优先级, 降序(_______非必填)
agenda-group "temp01"
lock-on-active true // 确保当前规则只匹配一次
	when
        $p : Person(age > 30);
    then
		System.out.println($p.getName() + "---" + $p.getAge());
end

rule "temp2"
salience 1 // 优先级, 降序(_______非必填)
lock-on-active true // 确保当前规则只匹配一次
	when
        $p : Person(name matches "曹.*");
    then
		System.out.println("name: " + $p.getName());
end

rule "temp3"
salience 10000 // 优先级, 降序(_______非必填)
agenda-group "temp01" // 必须设置焦点才会匹配当前规则kieSession.getAgenda().getAgendaGroup("temp01").setFocus()(_______非必填)
lock-on-active true // 确保当前规则只匹配一次(_______非必填)
	when
        $p : Person(age > 30);
    then
		System.out.println("name: " + $p.getName() + "---age: " + $p.getAge());
end

rule "temp4"
agenda-group "temp01"
lock-on-active true
	when
        $p : Person(age > 30);
    then
    	$p.setAge(99);
end